[colors]
ansi = [
    "#3c3836",
    "#d65d0e",
    "#b8bb26",
    "#fabd2f",
    "#83a598",
    "#d3869b",
    "#8ec07c",
    "#ebdbb2",
]
background = "#1D2122"
brights = [
    "#665c54",
    "#fb4934",
    "#b8bb26",
    "#fabd2f",
    "#83a598",
    "#d3869b",
    "#8ec07c",
    "#fbf1c7",
]
compose_cursor = "#fe8019"
cursor_bg = "#d5c4a1"
cursor_border = "#d5c4a1"
cursor_fg = "#1D2122"
foreground = "#d5c4a1"
scrollbar_thumb = "#665c54"
selection_bg = "#d5c4a1"
selection_fg = "#1D2122"

[colors.copy_mode_active_highlight_bg]
Color = "#665c54"

[colors.copy_mode_active_highlight_fg]
Color = "#fbf1c7"

[colors.copy_mode_inactive_highlight_bg]
Color = "#504945"

[colors.copy_mode_inactive_highlight_fg]
Color = "#ebdbb2"

[colors.quick_select_label_bg]
Color = "#504945"

[colors.quick_select_label_fg]
Color = "#ebdbb2"

[colors.quick_select_match_bg]
Color = "#665c54"

[colors.quick_select_match_fg]
Color = "#fbf1c7"
