[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
dotnet = "latest"
"dotnet:csharp-ls" = "latest"
node = "latest"
"pipx:eblume/mole" = "latest"
"pipx:simonw/llm" = "latest"
python = "latest"
rust = "latest"
uv = "latest"
"pipx:borgmatic" = "latest"

[tools."pipx:ansible-core"]
uvx = true
uvx_args = "--with botocore --with boto3"
version = "2.16.11"

[tools."pipx:devpi-server"]
version = "latest"
uvx = true
uvx_args = "--with devpi-web"

[tools."pipx:devpi-client"]
version = "latest"
uvx = true

[tools."pipx:osxphotos"]
version = "latest"
uvx = true
